services:
  - type: web
    name: iob-flask-app
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python nltk_downloader.py  # Optional: Downloads NLTK corpora
    startCommand: waitress-serve --listen=0.0.0.0:$PORT app_flask:app